name: ScheduleHQ
options:
  bundleIdPrefix: com.schedulehq
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  FirebaseAuth:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: "11.0.0"

targets:
  ScheduleHQ:
    type: application
    platform: iOS
    sources:
      - path: ScheduleHQ
        excludes:
          - "**/.gitkeep"
      - path: GoogleService-Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.schedulehq.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: S4LN25J73K
        ENABLE_PREVIEWS: YES
    dependencies:
      - package: FirebaseAuth
        product: FirebaseAuth
      - package: FirebaseAuth
        product: FirebaseFirestore
      - package: FirebaseAuth
        product: FirebaseMessaging

schemes:
  ScheduleHQ:
    build:
      targets:
        ScheduleHQ: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
